title = "Open Policy Agent"
baseURL = "https://openpolicyagent.org"
languageCode = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
googleAnalytics = "UA-84550302-1"

[params]
description = "Policy-based control for cloud native environments"
tagline = "Empower your administrators with flexible, fine-grained control across your entire stack."

[params.social]
twitter = "OpenPolicyAgent"

[params.versions]
latest = "0.10.3"

[params.logos]
sidebar = "/img/logos/opa-stacked-color.png"
navbar = "/img/logos/opa-icon-white.png"

[[params.home.buttons]]
url = "/docs/get-started"
title = "Get started"

[[params.home.buttons]]
url = "/docs"
title = "Learn more"

[menu]
[[menu.main]]
name = "Documentation"
url = "/docs"

[[menu.main]]
name = "Tutorials"
url = "/docs/get-started"

[[menu.social]]
name = "Medium"
url = "https://twitter.com/openpolicyagent"

[[menu.social]]
name = "Twitter"
url = "https://twitter.com/openpolicyagent"

[[menu.social]]
name = "Slack"
url = "http://slack.openpolicyagent.org/"

[[menu.social]]
name = "GitHub"
url = "https://github.com/open-policy-agent/opa"